import { Request, Response } from 'express';
import { catchAsync } from '../../shared/catchAsync';
import { sendResponse } from '../../shared/sendResponse';
import { UserRole } from '../../middleware/auth';
import { auth } from '../../lib/auth';
import { getAccessToken, getRefreshToken, setAccessTokenCookie } from '../../utils/tokenUtils';
import { prisma } from '../../lib/prisma'; // Added Prisma client
import { AppError } from '../../errors/AppError';
import { StatusCodes } from 'http-status-codes';

export const Register = catchAsync(async (req: Request, res: Response) => {
  const { name, email, password, role = UserRole.STUDENT, phone, imgUrl } = req.body;

  const headers = new Headers();
  Object.entries(req.headers).forEach(([key, value]) => {
      if (typeof value === "string") headers.set(key, value);
  });

  const response = await auth.api.signUpEmail({
      body: {
          name,
          email,
          password,
          role,
          phone,
          image: imgUrl
      },
      headers,
      asResponse: true
  });

  const responseData = await response.json();
  if (response.status >= 400 || !responseData.user) {
    return sendResponse(res, {
        httpStatusCode: response.status,
        success: false,
        message: responseData.message || 'Error occurred during registration.',
        data: null,
    });
  }

  const createdUserId = responseData.user.id;

  // Profile data creation transaction block (rollback on error)
  try {
      if (role === UserRole.STUDENT) {
          const { grade, institution, gender, interests } = req.body;
          await prisma.studentProfile.create({
              data: {
                  userId: createdUserId,
                  grade: grade || null,
                  institution: institution || null,
                  gender: gender || null,
                  interests: interests || null
              }
          });
      } else if (role === UserRole.TUTOR) {
          const { bio, price, experience, categoryId, gender, institution } = req.body;
          await prisma.tutorProfile.create({
              data: {
                  userId: createdUserId,
                  bio: bio || "Default bio description",
                  price: price || 0,
                  experience: experience || "0",
                  categoryId: categoryId || null,
                  gender: gender || null,
                  institution: institution || null
              }
          });
      }
  } catch (error: any) {
      // If profile creation fails, delete the user generated by Better-Auth to keep DB clean
      await prisma.user.delete({ where: { id: createdUserId } });

      return sendResponse(res, {
          httpStatusCode: 400,
          success: false,
          message: error.message || 'Failed to populate extra profile data. User creation rolled back.',
          data: null,
      });
  }

  // Fetch the final user WITH their correct nested profile to return to the client
  const finalUser = await prisma.user.findUnique({
      where: { id: createdUserId },
      include: {
          studentProfile: true,
          tutorProfile: true
      }
  });

  // Auto signin after register to get the better-auth session token
  const signInResponse = await auth.api.signInEmail({
      body: { email, password },
      headers,
      asResponse: true
  });

  const signInData = await signInResponse.json();

  const payload = {
    userId: responseData.user.id,
    role: role,
    email: email,
    name: finalUser?.name || name
  };

  const accessToken = getAccessToken(payload);
  const refreshToken = getRefreshToken(payload);

  setAccessTokenCookie(res, accessToken);

  // Returning BetterAuth token and session alongside custom JWTs
  sendResponse(res, {
    httpStatusCode: 201,
    success: true,
    message: 'User registered successfully!',
    data: { 
      accessToken, 
      refreshToken, 
      user: finalUser, // Includes the newly created relational profile data
      sessionToken: signInData.token 
    },
  });
});

export const loginUser = catchAsync(async (req: Request, res: Response) => {
    const { email, password } = req.body;
  
    const headers = new Headers();
    Object.entries(req.headers).forEach(([key, value]) => {
        if (typeof value === "string") headers.set(key, value);
    });
  
    const signInResponse = await auth.api.signInEmail({
         body: { email, password },
         headers,
         asResponse: true
    });
  
    const responseData = await signInResponse.json();
    if (signInResponse.status >= 400 || !responseData.user) {
        return sendResponse(res, {
            httpStatusCode: signInResponse.status,
            success: false,
            message: responseData.message || 'Invalid email or password',
            data: null,
        });
    }

    // Block non-active users from logging in.
    const dbUser = await prisma.user.findUnique({
      where: { id: responseData.user.id },
      select: { status: true },
    });
    if (!dbUser || dbUser.status !== "ACTIVE") {
      return sendResponse(res, {
        httpStatusCode: StatusCodes.FORBIDDEN,
        success: false,
        message: "Your account is inactive or deleted. Please contact admin.",
        data: null,
      });
    }

    const payload = {
      userId: responseData.user.id,
      role: responseData.user.role || UserRole.STUDENT,
      email: email,
      name: responseData.user.name
    };
  
    const accessToken = getAccessToken(payload);
    const refreshToken = getRefreshToken(payload);
  
    setAccessTokenCookie(res, accessToken);
  
    // Returning BetterAuth token and session alongside custom JWTs
    sendResponse(res, {
      httpStatusCode: 200,
      success: true,
      message: 'Logged in successfully!',
      data: { 
        accessToken, 
        refreshToken, 
        user: responseData.user,
        sessionToken: responseData.token // Mapping better-auth's exact token string here
      },
    });
});

export const changePassword = catchAsync(async (req: Request, res: Response) => {
    const user = req.user;
    if (!user) throw new AppError(StatusCodes.UNAUTHORIZED, "Unauthorized");

    const { oldPassword, newPassword, revokeOtherSessions = false } = req.body;
    if (!oldPassword || !newPassword) throw new AppError(StatusCodes.BAD_REQUEST, "Old and new passwords are required");

    // Better-auth authenticates via its own session cookie. Our JWT is only for our `auth()` middleware.
    const headers = new Headers();
    const sessionToken = (req.headers["x-session-token"] as string | undefined) ?? undefined;
    if (!sessionToken) {
        throw new AppError(StatusCodes.UNAUTHORIZED, "Session token missing. Please login again.");
    }
    headers.set("cookie", `better-auth.session_token=${sessionToken}`);

    let result: any;
    try {
        result = await auth.api.changePassword({
            body: {
                newPassword,
                currentPassword: oldPassword,
                revokeOtherSessions,
            },
            headers,
        });
    } catch (e: any) {
        // Normalize better-auth errors
        const msg = String(e?.message ?? "Unauthorized");
        throw new AppError(StatusCodes.UNAUTHORIZED, msg);
    }

    if (revokeOtherSessions) {
        // Revoke OTHER sessions, keep current session alive.
        // To do this we need the current session token (sent by frontend as x-session-token).
        const currentToken = (req.headers["x-session-token"] as string | undefined) ?? undefined;
        if (currentToken) {
            await prisma.session.deleteMany({
                where: { userId: user.id, NOT: [{ token: currentToken }] }
            });
        }
    }

    sendResponse(res, {
        httpStatusCode: 200,
        success: true,
        message: revokeOtherSessions
            ? 'Password changed successfully. Other sessions revoked.'
            : 'Password changed successfully.',
        data: {
            redirectUrl: "/"
        },
    });
});

export const logoutUser = catchAsync(async (req: Request, res: Response) => {
    const headers = new Headers();
    Object.entries(req.headers).forEach(([key, value]) => {
        if (typeof value === "string") headers.set(key, value);
    });

    try {
        await auth.api.signOut({
            headers
        });
    } catch(err) {
        // Ignore better-auth signout errors if session already dead
    }

    res.clearCookie("accessToken");
    res.clearCookie("refreshToken");
    res.clearCookie("better-auth.session_token");

    sendResponse(res, {
        httpStatusCode: 200,
        success: true,
        message: 'Logged out successfully!',
        data: null,
    });
});

